export enum Provider {
	GITHUB = "GITHUB",
	EMAIL = "EMAIL",
}

export enum LinkProviders {
	GOOGLE = "GOOGLE",
	FACEBOOK = "FACEBOOK",
	INSTAGRAM = "INSTAGRAM",
	WHATS_UP = "WHATS_UP",
	APPLE = "APPLE",
	ALI_BABA = "ALI_BABA",
	ALI_EXPRESS = "ALI_EXPRESS",
	TWITTER = "TWITTER",
	GITHUB = "GITHUB",
	PERSONAL = "PERSONAL",
}
